package exceptionHandleDemo;

public class Exception2 {
	
	public static void main(String[] args) {
		
		
		System.out.println("welcome all");
		
		int number;
		
		number = 100/0;  //logically we are wrong here
		
		System.out.println(number);
		
		System.out.println("remaininig code1");
		System.out.println("remaininig code2");
		
		
	}

}
